server:
  port: 0
spring:  application:    name: User-Service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true 
      path: /console
eureka:  client:    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true        